version: '3.8'

services:
  infinity-stream:
    image: ghcr.io/${GITHUB_USERNAME}/personal-radio-stream:latest
    volumes:
      - ./downloaded_media:/app/downloaded_media
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - TZ=America/Denver
      - TRELLO_API_KEY=${TRELLO_API_KEY}
      - TRELLO_TOKEN=${TRELLO_TOKEN}
      - TRELLO_BOARD_NAME=🧱 Radio
    command: >
      sh -c "
        echo 'Environment variables:' &&
        echo TRELLO_API_KEY=$${TRELLO_API_KEY} &&
        echo TRELLO_TOKEN=$${TRELLO_TOKEN} &&
        echo TRELLO_BOARD_NAME=$${TRELLO_BOARD_NAME} &&
        echo 'Generated config.ini:' &&
        envsubst < config.template.ini > config.ini &&
        cat config.ini &&
        python start_stream.py
      "

  cleanup:
    image: alpine:latest
    volumes:
      - ./downloaded_media:/media_to_clean
    environment:
      - TZ=America/Denver
    command: >
      sh -c "
        echo '0 4 * * * rm -rf /media_to_clean/*' > /etc/crontabs/root &&
        crond -f -l 2
      "
    restart: unless-stopped
