version: '3.8'

services:
  infinity-stream:
    image: ghcr.io/${GITHUB_USERNAME}/personal-radio-stream:latest
    volumes:
      - ./downloaded_media:/app/downloaded_media
    ports:
      - "8554:8554"
    restart: unless-stopped
    environment:
      - TZ=UTC
      - TRELLO_API_KEY=${TRELLO_API_KEY}
      - TRELLO_TOKEN=${TRELLO_TOKEN}
      - TRELLO_BOARD_NAME= Radio
    # Add labels for Watchtower to monitor this container
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # Check for updates every 30 minutes
      - WATCHTOWER_POLL_INTERVAL=1800
      # Clean up old images after updating
      - WATCHTOWER_CLEANUP=true
      # Only update containers with the enable label
      - WATCHTOWER_LABEL_ENABLE=true
      # Add GitHub Container Registry authentication
      - WATCHTOWER_REGISTRY_USERNAME=${GITHUB_USERNAME}
      - WATCHTOWER_REGISTRY_PASSWORD=${GITHUB_TOKEN}
    restart: unless-stopped